import type { Review, KPIData, SentimentPoint } from '../types';

export const MOCK_KPI: KPIData = {
  avg_rating: 4.6,
  rating_trend: 8,
  monthly_growth: 11,
  avg_response_time_hours: 2.1,
  positive_pct: 82,
  positive_count: 164,
  pending_count: 5,
};

export const MOCK_SENTIMENT_WEEK: SentimentPoint[] = [
  { day: "א'", positive: 70, critical: 10 },
  { day: "ב'", positive: 80, critical: 5  },
  { day: "ג'", positive: 75, critical: 8  },
  { day: "ד'", positive: 90, critical: 3  },
  { day: "ה'", positive: 85, critical: 6  },
  { day: "ו'", positive: 60, critical: 15 },
  { day: "ש'", positive: 78, critical: 7  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    business_id: 'demo-business-1',
    reviewer_name: 'יוסי אברהם',
    reviewer_initials: 'יא',
    platform: 'google',
    rating: 5,
    content: 'הגעתי עם שאיפת גלגל באמצע היום, עמי תיקן תוך עשר דקות ולא לקח אגורה. יחס אנושי ומקצועי שלא מוצאים בכל מקום. אחלה מוסך!',
    sentiment: 'very_positive',
    status: 'replied',
    reply_text: 'יוסי, תודה רבה! שמחנו לעזור. נסיעה בטוחה!',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: '2',
    business_id: 'demo-business-1',
    reviewer_name: 'מרים כהן',
    reviewer_initials: 'מכ',
    platform: 'google',
    rating: 5,
    content: 'עמי מקצוען אמיתי. אבחן את הבעיה במנוע תוך דקות, תיקן ביום אחד ובמחיר שהיה נמוך ממה שציפיתי. כבר שנתיים הולכת רק אליו.',
    sentiment: 'very_positive',
    status: 'replied',
    reply_text: 'מרים, תודה! כיף לראות פנים מוכרות. נשמח לראותך לטיפול הבא!',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: '3',
    business_id: 'demo-business-1',
    reviewer_name: 'דוד לוי',
    reviewer_initials: 'דל',
    platform: 'facebook',
    rating: 4,
    content: 'שירות טוב ומקצועי. מסבירים כל פעולה לפני שמבצעים ולא מנסים למכור דברים מיותרים. זמן ההמתנה היה קצת ארוך אבל שווה.',
    sentiment: 'positive',
    status: 'pending',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: '4',
    business_id: 'demo-business-1',
    reviewer_name: 'רונית שמיר',
    reviewer_initials: 'רש',
    platform: 'google',
    rating: 2,
    content: 'חיכיתי 3 שעות לטיפול שאמרו שיקח שעה. לאורך הזמן לא עדכנו אותי על העיכוב ונאלצתי לשאול בעצמי. לא קיבלתי הסבר מספק.',
    sentiment: 'critical',
    status: 'pending',
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: '5',
    business_id: 'demo-business-1',
    reviewer_name: 'ניר גולן',
    reviewer_initials: 'נג',
    platform: 'google',
    rating: 5,
    content: 'הרכב לא נדלק ב-6 בבוקר לפני עבודה. התקשרתי לעמי, הוא הגיע עד הבית תוך חצי שעה ותיקן במקום. מקצוענות אחרת לגמרי!',
    sentiment: 'very_positive',
    status: 'replied',
    reply_text: 'ניר, שמחנו לעזור! כזה בוקר לא כיף. שנסע לשלום 🙂',
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: '6',
    business_id: 'demo-business-1',
    reviewer_name: 'אלי מזרחי',
    reviewer_initials: 'אמ',
    platform: 'google',
    rating: 5,
    content: 'מוסך מהימן ואמין. הולך אליהם כבר 5 שנים עם שתי המכוניות שלי. מחירים הוגנים, עבודה נקייה, ותמיד מסבירים מה עשו.',
    sentiment: 'very_positive',
    status: 'replied',
    reply_text: 'אלי, חבר ותיק! תודה על האמון. נשמח להמשיך לשרת אותך.',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: '7',
    business_id: 'demo-business-1',
    reviewer_name: 'תמר לבנה',
    reviewer_initials: 'תל',
    platform: 'facebook',
    rating: 3,
    content: 'מקצועי ועושה עבודה טובה, אבל המחירים קצת גבוהים יחסית לאזור. כדאי להשוות מחירים לפני. השירות עצמו היה בסדר גמור.',
    sentiment: 'neutral',
    status: 'pending',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: '8',
    business_id: 'demo-business-1',
    reviewer_name: 'שלומי פרץ',
    reviewer_initials: 'שפ',
    platform: 'google',
    rating: 5,
    content: 'עשו לי טסט שנתי תוך שעה בדיוק, ובלי הפתעות מחיר. הצוות אדיב, המקום נקי ומסודר. ממליץ בחום לכל תושבי פתח תקווה.',
    sentiment: 'very_positive',
    status: 'replied',
    reply_text: 'שלומי, תודה! שמחים לשמוע. נסיעות בטוחות!',
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
  },
];
