import type { Review, KPIData, SentimentPoint } from '../types';

export const MOCK_KPI: KPIData = {
  avg_rating: 4.8,
  rating_trend: 12,
  monthly_growth: 14,
  avg_response_time_hours: 1.2,
  positive_pct: 92,
  positive_count: 840,
  pending_count: 12,
};

export const MOCK_SENTIMENT_WEEK: SentimentPoint[] = [
  { day: "א'", positive: 65, critical: 8 },
  { day: "ב'", positive: 72, critical: 12 },
  { day: "ג'", positive: 68, critical: 6 },
  { day: "ד'", positive: 85, critical: 4 },
  { day: "ה'", positive: 92, critical: 3 },
  { day: "ו'", positive: 70, critical: 9 },
  { day: "ש'", positive: 78, critical: 7 },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    business_id: 'b1',
    reviewer_name: 'אבי קדוש',
    reviewer_initials: 'AK',
    platform: 'google',
    rating: 5,
    content: 'שירות מעולה! הצוות היה מקצועי ואדיב מאוד. ממליץ בחום לכולם.',
    sentiment: 'very_positive',
    status: 'replied',
    created_at: '2024-12-01T10:00:00Z',
  },
  {
    id: '2',
    business_id: 'b1',
    reviewer_name: 'רעות לוין',
    reviewer_initials: 'RL',
    platform: 'facebook',
    rating: 2,
    content: 'המוצר הגיע פגום ולא הצלחתי להשיג את שירות הלקוחות.',
    sentiment: 'critical',
    status: 'pending',
    created_at: '2024-12-02T14:30:00Z',
  },
  {
    id: '3',
    business_id: 'b1',
    reviewer_name: 'יוסי כהן',
    reviewer_initials: 'YK',
    platform: 'google',
    rating: 1,
    content: 'השירות היה מאכזב מאוד, חיכיתי מעל שעה לנציג ובסוף לא קיבלתי מענה.',
    sentiment: 'critical',
    status: 'pending',
    created_at: '2024-12-03T09:15:00Z',
  },
  {
    id: '4',
    business_id: 'b1',
    reviewer_name: 'מיכל לוי',
    reviewer_initials: 'ML',
    platform: 'tripadvisor',
    rating: 2,
    content: 'ציפיתי ליותר בהתחשב במחיר. האוכל היה בינוני.',
    sentiment: 'critical',
    status: 'pending',
    created_at: '2024-12-04T18:00:00Z',
  },
  {
    id: '5',
    business_id: 'b1',
    reviewer_name: 'דניאל ר.',
    reviewer_initials: 'DR',
    platform: 'wolt',
    rating: 3,
    content: 'בסך הכל בסדר אבל יש מקום לשיפור במהירות המשלוח.',
    sentiment: 'neutral',
    status: 'pending',
    created_at: '2024-12-05T12:45:00Z',
  },
  {
    id: '6',
    business_id: 'b1',
    reviewer_name: 'שרה מזרחי',
    reviewer_initials: 'SM',
    platform: 'google',
    rating: 5,
    content: 'חוויה נהדרת מהתחלה ועד הסוף! יחזרו בהחלט.',
    sentiment: 'very_positive',
    status: 'replied',
    created_at: '2024-12-06T11:00:00Z',
  },
  {
    id: '7',
    business_id: 'b1',
    reviewer_name: 'נועם הרצוג',
    reviewer_initials: 'NH',
    platform: 'facebook',
    rating: 4,
    content: 'שירות טוב, זמני המתנה סבירים. בהחלט אמליץ.',
    sentiment: 'positive',
    status: 'replied',
    created_at: '2024-12-07T16:20:00Z',
  },
  {
    id: '8',
    business_id: 'b1',
    reviewer_name: 'טל ברק',
    reviewer_initials: 'TB',
    platform: 'google',
    rating: 5,
    content: 'הכי טוב שיש! כל פעם מחדש מופתע לטובה.',
    sentiment: 'very_positive',
    status: 'replied',
    created_at: '2024-12-08T08:30:00Z',
  },
];
